# Generated by Django 4.2.1 on 2023-06-01 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_title_alter_listing_winning_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winning_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_winning_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
