# Generated by Django 4.2.1 on 2023-06-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_winning_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
