# Generated by Django 4.2.1 on 2023-06-01 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='on_watchlist',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
