# Generated by Django 4.2.1 on 2023-06-02 13:20

from django.db import migrations


def export_customer_company(apps, schema_editor):
    Comment = apps.get_model('auctions', 'Comment')
    Listing = apps.get_model('auctions', 'Listing')
    for customer in Comment.objects.all():
        customer.listing = Listing.objects.get_or_create(id=1)[0]
        customer.save()



class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_active'),
    ]

    operations = [
        migrations.RunPython(export_customer_company),
    ] 
